import type { Metadata } from "next";
import { Tenor_Sans } from "next/font/google";

import "./globals.css";

const tenor = Tenor_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trading Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={tenor.className}>{children}</body>
    </html>
  );
}
